CREATE DATABASE QLNOITHAT
GO
USE QLNOITHAT
GO
CREATE TABLE NHANVIEN(
	ID INT IDENTITY(1, 1) PRIMARY KEY,
	MANV VARCHAR(50) NOT NULL,
	HOTEN NVARCHAR(50) NOT NULL,
	NGAYSINH DATETIME,
	DIACHI NVARCHAR(50) Not Null,
	SDT VARCHAR(10) Not Null,
	AVARTAR VARCHAR(50),
	EMAIL NVARCHAR(50) Not Null,

)
GO
create table ACCOUNT (
	ID int identity(1 ,1) primary key,
	TENDN varchar(255) not null,
	PASS varchar (255) not null,
)
GO
CREATE TABLE KHACHHANG(
	ID INT IDENTITY(1, 1) PRIMARY KEY,
	HOTEN NVARCHAR(50) Not Null,
	DIACHI NVARCHAR(50) Not Null,
	SDT VARCHAR(10) Not Null,
	AVARTAR VARCHAR(50),
	EMAIL NVARCHAR(50) Not Null,
)
GO
CREATE TABLE LOAISANPHAM(
	ID INT IDENTITY(1, 1) PRIMARY KEY,
	TENLSP NVARCHAR(50) Not Null,
)
GO
CREATE TABLE SANPHAM(
	ID INT IDENTITY(1, 1) PRIMARY KEY,
	LOAISANPHAMID INT FOREIGN KEY REFERENCES LOAISANPHAM(ID),
	MASP VARCHAR(50) NOT NULL,
	TENSP NVARCHAR(50) NOT NULL,
	SOLUONGTON INT,
	IMG VARCHAR(50),
	MOTA NVARCHAR(MAX) NOT NULL,
	GIABAN INT NOT NULL,
	CHATLIEU NVARCHAR(50) NOT NULL,
	MAUSAC NVARCHAR(50) NOT NULL,
	BAOHANH NVARCHAR(50) NOT NULL
)
GO
CREATE TABLE PHUONGTHUCTHANHTOAN(
	ID INT IDENTITY(1, 1) PRIMARY KEY,
	TENPT NVARCHAR(50) NOT NULL,
)
GO
CREATE TABLE TINHTRANG(
	ID INT IDENTITY(1, 1) PRIMARY KEY,
	TENTT NVARCHAR(50) NOT NULL
)
GO
CREATE TABLE HOADON(
	ID INT IDENTITY(1, 1) PRIMARY KEY,
	IDKH INT FOREIGN KEY REFERENCES KHACHHANG(ID),
	NGAYDATHANG DATETIME NOT NULL,
	NGAYGIAOHANG DATETIME NOT NULL,
	DIACHIGIAOHANG NVARCHAR(50) NOT NULL,
	IDNV INT FOREIGN KEY REFERENCES NHANVIEN(ID),
	IDPT INT FOREIGN KEY REFERENCES PHUONGTHUCTHANHTOAN(ID),
	IDTT INT FOREIGN KEY REFERENCES TINHTRANG(ID),
)
go
CREATE TABLE CTHOADON(
	ID INT IDENTITY(1, 1) PRIMARY KEY,
	IDHD INT FOREIGN KEY REFERENCES HOADON(ID),
	IDSP INT FOREIGN KEY REFERENCES SANPHAM(ID),
	SOLUONG INT NOT NULL,
	DONGIA INT NOT NULL,
)
GO
INSERT INTO CTHOADON VALUES (1, 2, 3, 490000)
GO
CREATE TABLE BINHLUAN(
	ID INT IDENTITY(1, 1) PRIMARY KEY,
	IDKH INT FOREIGN KEY REFERENCES KHACHHANG(ID),
	IDSP INT FOREIGN KEY REFERENCES SANPHAM(ID),
	NOIDUNGBL NVARCHAR(255) NOT NULL,
	THOIGIANBL DATETIME NOT NULL,

)
go
INSERT INTO BINHLUAN VALUES (2, 1, 'haha', '29/4/2023')
go
SELECT * FROM KHACHHANG
go
ALTER TABLE KHACHHANG ADD MAKH VARCHAR(50) NOT NULl
GO
ALTER TABLE NHANVIEN ADD TENDN VARCHAR(50) NOT NULL, PASS VARCHAR(255) NOT NULL, ISADMIN BIT NOT NULL
GO
GO
INSERT INTO LOAISANPHAM VALUES (N'GHẾ')
INSERT INTO LOAISANPHAM VALUES (N'TỦ QUẦN ÁO')
INSERT INTO LOAISANPHAM VALUES (N'SOFA')
INSERT INTO LOAISANPHAM VALUES (N'KỆ TỦ')
INSERT INTO LOAISANPHAM VALUES (N'GIƯỜNG')
INSERT INTO LOAISANPHAM VALUES (N'BÀN')
INSERT INTO LOAISANPHAM VALUES (N'BỘ PHÒNG KHÁCH')
INSERT INTO LOAISANPHAM VALUES (N'BỘ PHÒNG NGỦ')
INSERT INTO LOAISANPHAM VALUES (N'BỘ PHÒNG ĂN')
INSERT INTO LOAISANPHAM VALUES (N'BỘ SẢN PHẨM')
go
select * from SANPHAM
GO
GO
INSERT INTO PHUONGTHUCTHANHTOAN VALUES ('Thanh toán khi nhận hàng')
INSERT INTO PHUONGTHUCTHANHTOAN VALUES ('Thẻ tín dụng')
go
GO
INSERT INTO TINHTRANG VALUES ('Chờ xác nhận')
INSERT INTO TINHTRANG VALUES ('Chờ lấy hàng')
INSERT INTO TINHTRANG VALUES ('Đang giao')
go
INSERT INTO HOADON VALUES (5, '30/4/2023', '1/5/2023', 12, 1, 1)
go
SELECT * FROM HOADON
GO
select * from cthoadon
go

